version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - './app:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './_docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root